version: '3.8'

services:
  client:
    build:
      context: ./resultanalysis-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ./resultanalysis-client/.env
    depends_on:
      - server

  server:
    build:
      context: ./resultanalysis-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./resultanalysis-server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
